### PR TITLE
Update paper with affiliation

### PR DESCRIPTION
**Pull request by betatim**
Should this also include my email or is having Chris' enough?

### CODE REVIEW

**Comment by choldgraf** [comment]
good question, @mpacer do you know?

**Comment by mpacer** [comment]
It should have everyone’s email who wishes to be responsible for being contacted about the article.

At least that’s the position that I would suggest if we were to need to discuss it. I’m
Just speaking as an author here not an editor. I could be convinced otherwise as an editor so this opinion should be taken as my first inclination, not a statement of policy. The committee would need to come to a consensus around some policy if we are concerned about it. I plan to take a pass over this this weekend.

So I suggest as for being an author with an email we follow the above policy, but we may need to revert that if people on the committee disagree. I plan to add everyone’s email so that the default is to be responsible for it. But I’ll do so by contacting people about which email they want included (with the option of `None` always available).

**Comment by mpacer** [comment]
At least that’s the position that I would suggest if we were to need to discuss it. I’m
Just speaking as an author here not an editor. I could be convinced otherwise.

**Comment by betatim** [comment]
Added my email.

**Comment by choldgraf** [comment]
thanks @betatim !!!

**Pull request merged**
